views.filter.latest_revision:
  type: views_filter
  label: 'Latest revision'
  mapping:
    value:
      type: string
      label: 'Value'

node.type.*.third_party.content_moderation:
  type: mapping
  label: 'Enable moderation states for this node type'
  mapping:
    workflow:
      type: string
      label: 'Workflow'

block_content.type.*.third_party.content_moderation:
  type: mapping
  label: 'Enable moderation states for this block content type'
  mapping:
    workflow:
      type: string
      label: 'Workflow'

workflow.type_settings.content_moderation:
  type: mapping
  mapping:
    states:
      type: sequence
      label: 'Additional state configuration for content moderation'
      sequence:
        type: mapping
        label: 'States'
        mapping:
          published:
            type: boolean
            label: 'Is published'
          default_revision:
            type: boolean
            label: 'Is default revision'
    entity_types:
      type: sequence
      label: 'Entity types'
      sequence:
        type: sequence
        label: 'Bundles'
        sequence:
          type: string
          label: 'Bundle ID'
